/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutDottxtRouteImport } from './routes/about[.]txt'
import { Route as IndexDottxtRouteImport } from './routes/index[.]txt'
import { Route as InsightsDottxtRouteImport } from './routes/insights[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as ProtocolsDottxtRouteImport } from './routes/protocols[.]txt'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesDottxtRouteImport } from './routes/services[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as InsightsTxtSlugRouteImport } from './routes/insights.txt.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDottxtRoute = AboutDottxtRouteImport.update({
  id: '/about.txt',
  path: '/about.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDottxtRoute = IndexDottxtRouteImport.update({
  id: '/index.txt',
  path: '/index.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsDottxtRoute = InsightsDottxtRouteImport.update({
  id: '/insights.txt',
  path: '/insights.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsDottxtRoute = ProtocolsDottxtRouteImport.update({
  id: '/protocols.txt',
  path: '/protocols.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDottxtRoute = ServicesDottxtRouteImport.update({
  id: '/services.txt',
  path: '/services.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsTxtSlugRoute = InsightsTxtSlugRouteImport.update({
  id: '/insights/txt/$slug',
  path: '/insights/txt/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about.txt': typeof AboutDottxtRoute
  '/index.txt': typeof IndexDottxtRoute
  '/insights.txt': typeof InsightsDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/protocols': typeof ProtocolsRoute
  '/protocols.txt': typeof ProtocolsDottxtRoute
  '/services': typeof ServicesRoute
  '/services.txt': typeof ServicesDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/insights/txt/$slug': typeof InsightsTxtSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about.txt': typeof AboutDottxtRoute
  '/index.txt': typeof IndexDottxtRoute
  '/insights.txt': typeof InsightsDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/protocols': typeof ProtocolsRoute
  '/protocols.txt': typeof ProtocolsDottxtRoute
  '/services': typeof ServicesRoute
  '/services.txt': typeof ServicesDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights': typeof InsightsIndexRoute
  '/insights/txt/$slug': typeof InsightsTxtSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about.txt': typeof AboutDottxtRoute
  '/index.txt': typeof IndexDottxtRoute
  '/insights.txt': typeof InsightsDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/protocols': typeof ProtocolsRoute
  '/protocols.txt': typeof ProtocolsDottxtRoute
  '/services': typeof ServicesRoute
  '/services.txt': typeof ServicesDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/insights/txt/$slug': typeof InsightsTxtSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about.txt'
    | '/index.txt'
    | '/insights.txt'
    | '/llms.txt'
    | '/protocols'
    | '/protocols.txt'
    | '/services'
    | '/services.txt'
    | '/sitemap.xml'
    | '/insights/$slug'
    | '/insights/'
    | '/insights/txt/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about.txt'
    | '/index.txt'
    | '/insights.txt'
    | '/llms.txt'
    | '/protocols'
    | '/protocols.txt'
    | '/services'
    | '/services.txt'
    | '/sitemap.xml'
    | '/insights/$slug'
    | '/insights'
    | '/insights/txt/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about.txt'
    | '/index.txt'
    | '/insights.txt'
    | '/llms.txt'
    | '/protocols'
    | '/protocols.txt'
    | '/services'
    | '/services.txt'
    | '/sitemap.xml'
    | '/insights/$slug'
    | '/insights/'
    | '/insights/txt/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutDottxtRoute: typeof AboutDottxtRoute
  IndexDottxtRoute: typeof IndexDottxtRoute
  InsightsDottxtRoute: typeof InsightsDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ProtocolsRoute: typeof ProtocolsRoute
  ProtocolsDottxtRoute: typeof ProtocolsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  ServicesDottxtRoute: typeof ServicesDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  InsightsTxtSlugRoute: typeof InsightsTxtSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about.txt': {
      id: '/about.txt'
      path: '/about.txt'
      fullPath: '/about.txt'
      preLoaderRoute: typeof AboutDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.txt': {
      id: '/index.txt'
      path: '/index.txt'
      fullPath: '/index.txt'
      preLoaderRoute: typeof IndexDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights.txt': {
      id: '/insights.txt'
      path: '/insights.txt'
      fullPath: '/insights.txt'
      preLoaderRoute: typeof InsightsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols.txt': {
      id: '/protocols.txt'
      path: '/protocols.txt'
      fullPath: '/protocols.txt'
      preLoaderRoute: typeof ProtocolsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services.txt': {
      id: '/services.txt'
      path: '/services.txt'
      fullPath: '/services.txt'
      preLoaderRoute: typeof ServicesDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/txt/$slug': {
      id: '/insights/txt/$slug'
      path: '/insights/txt/$slug'
      fullPath: '/insights/txt/$slug'
      preLoaderRoute: typeof InsightsTxtSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutDottxtRoute: AboutDottxtRoute,
  IndexDottxtRoute: IndexDottxtRoute,
  InsightsDottxtRoute: InsightsDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ProtocolsRoute: ProtocolsRoute,
  ProtocolsDottxtRoute: ProtocolsDottxtRoute,
  ServicesRoute: ServicesRoute,
  ServicesDottxtRoute: ServicesDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  InsightsTxtSlugRoute: InsightsTxtSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
